[package]
name = "cargo-gpu"
version = "0.1.0"
edition = "2021"
description = "Generates shader .spv files from rust-gpu shader crates"
repository = "https://github.com/Rust-GPU/cargo-gpu"
readme = "../../README.md"
keywords = ["gpu", "compiler", "rust-gpu"]
license = "MIT OR Apache-2.0"
default-run = "cargo-gpu"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "embed-legacy-target-specs" ]
embed-legacy-target-specs = [ "dep:legacy_target_specs" ]

[dependencies]
cargo_metadata.workspace = true
anyhow.workspace = true
spirv-builder = { workspace = true, features = ["clap", "watch"] }
clap.workspace = true
directories.workspace = true
env_logger.workspace = true
log.workspace = true
relative-path.workspace = true
serde.workspace = true
serde_json.workspace = true
crossterm.workspace = true
semver.workspace = true

legacy_target_specs = { workspace = true, optional = true }

[dev-dependencies]
test-log.workspace = true
cargo_metadata = { workspace = true, features = ["builder"] }
cargo-util-schemas = "0.8.2"

[lints]
workspace = true
